service: node11

provider:
  name: aws
  runtime: provided

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
    layers:
      - arn:aws:lambda:us-east-1:553035198032:layer:nodejs11:3